name: Package and Publish

on:
  push:
    branches: [main]

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release.outputs.release_created }}
      tag: ${{ steps.release.outputs.tag_name }}

    steps:
    - uses: GoogleCloudPlatform/release-please-action@v2
      id: release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release-type: simple
        default-branch: main
        changelog-types: '[{"type": "feat", "section": "New Features"}, {"type": "imp", "section": "Improvements"}, {"type": "ref", "section": "Refactors", }, {"type": "fix", "section": "Bug Fixes"}, {"type": "rev", "section": "Reverts"}, {"type": "doc", "section": "Documentation"}, {"type": "misc", "section": "Miscellaneous"}]'

  build:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.released }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Setup
      run: |
        pip install --upgrade pip
        pip install --upgrade build wheel setuptools
    
    - name: Build
      run: python -m build

    - name: Test sdist
      # The audience of source distributions are developers/contributors, the
      # unittests are included in this distribution. We use those packaged tests
      # to test the build.
      run: |
        mkdir aioircd-sdist
        tar -xf dist/*.tar.gz -C aioircd-sdist
        cd aioircd-sdist/*/
        python -m venv venv-sdist
        venv-sdist/bin/pip install -e .
        venv-sdist/bin/python -m unittest
        cd ../..

    - name: Test wheel
      # The audience of wheel distributions are end-users/sysadmins, the
      # unittests are NOT included in this distribution. We use the tests from
      # the non-packaged source code to test the build.
      run: |
        python -m venv venv-wheel
        venv-wheel/bin/pip install dist/*.whl
        venv-wheel/bin/python -m unittest

    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
